<?php
	function theme_locals($label) {
$allowed_html_array = array(
    'a' => array(
        'href' => true,
        'title' => true,
    ),
    'abbr' => array(
        'title' => true,
    ),
    'acronym' => array(
        'title' => true,
    ),
    'b' => array(),
    'blockquote' => array(
        'cite' => true,
    ),
    'cite' => array(),
    'code' => array(),
    'del' => array(
        'datetime' => true,
    ),
    'em' => array(),
    'i' => array(),
    'q' => array(
        'cite' => true,
    ),
    'strike' => array(),
    'strong' => array(),
	'span' => array(),
);
		$locals = array(
			//general
			'most_popular' => buzzblogpro_getVariable('most_popular_text') ? buzzblogpro_getVariable('most_popular_text') : esc_html__('Most popular posts', 'buzzblogpro'),
			'reply' => buzzblogpro_getVariable('reply_text') ? buzzblogpro_getVariable('reply_text') : esc_html__('Reply', 'buzzblogpro'),
			'home' => esc_html__('Home', 'buzzblogpro'),
			'back_to_top' => esc_html__('Back To Top', 'buzzblogpro'),
			'blog_related' => buzzblogpro_getVariable('youmightalsolike_text') ? buzzblogpro_getVariable('youmightalsolike_text') : esc_html__('You Might Also Like', 'buzzblogpro'),
			'min_read' => buzzblogpro_getVariable('min_read_text') ? buzzblogpro_getVariable('min_read_text') : esc_html__('min read', 'buzzblogpro'),
			'location' => buzzblogpro_getVariable('location_text') ? buzzblogpro_getVariable('location_text') : esc_html__('Location:', 'buzzblogpro'),
			'text_before_author' => buzzblogpro_getVariable('before_author_text') ? buzzblogpro_getVariable('before_author_text') : esc_html__('By', 'buzzblogpro'),
			'trending' => buzzblogpro_getVariable('trending_text') ? buzzblogpro_getVariable('trending_text') : esc_html__('Trending this week', 'buzzblogpro'),
			'views' => buzzblogpro_getVariable('views_text') ? buzzblogpro_getVariable('views_text') : esc_html__('views', 'buzzblogpro'),
			'no' => esc_html__('No', 'buzzblogpro'),
			'yes' => esc_html__('Yes', 'buzzblogpro'),
			'no_more_posts' => esc_html__('No more posts', 'buzzblogpro'),
			'slow_speed' => esc_html__('Slow', 'buzzblogpro'),
			'normal_speed' => esc_html__('Normal', 'buzzblogpro'),
			'fast_speed' => esc_html__('Fast', 'buzzblogpro'),
			'normal_size' => esc_html__('Normal size', 'buzzblogpro'),
			'large_size' => esc_html__('Large size', 'buzzblogpro'),
			'font_size' => esc_html__('Font Size', 'buzzblogpro'),
			'lineheight' => esc_html__('Lineheight', 'buzzblogpro'),
			'font_face' => esc_html__('Font Face', 'buzzblogpro'),
			'character_sets' => esc_html__('Character Sets', 'buzzblogpro'),
			'font_style' => esc_html__('Font Style', 'buzzblogpro'),
			'color' => esc_html__('Color', 'buzzblogpro'),
			'import' => esc_html__('Import', 'buzzblogpro'),
			'export' => esc_html__('Export', 'buzzblogpro'),
			'done' => esc_html__('Done', 'buzzblogpro'),
			'error' => esc_html__('Error', 'buzzblogpro'),
			'success' => esc_html__('success', 'buzzblogpro'),
			'upload' => esc_html__('Upload', 'buzzblogpro'),
			'try_again' => esc_html__('try again', 'buzzblogpro'),
			'finish' => esc_html__('Finish', 'buzzblogpro'),
			'skip' => esc_html__('Skip this step', 'buzzblogpro'),
			'install_next' => esc_html__('next', 'buzzblogpro'),
			'none' => esc_html__('None', 'buzzblogpro'),
			'date' => esc_html__('Date', 'buzzblogpro'),
			'title' => esc_html__('Title', 'buzzblogpro'),
			'info' => esc_html__('Info', 'buzzblogpro'),
			'rand' => esc_html__('Random', 'buzzblogpro'),
			'comment_count' => esc_html__('Comment count', 'buzzblogpro'),
			'enable_lightbox' => esc_html__('Enable Lightbox', 'buzzblogpro'),
			'enable_lightbox_desc' => esc_html__('Check this to enable the lightbox.', 'buzzblogpro'),
			'permalink_to' => esc_html__('Permalink', 'buzzblogpro'),
			'read_more' => esc_html__('VIEW POST', 'buzzblogpro'),
			'view_all' => esc_html__('View all', 'buzzblogpro'),
			'width' => esc_html__('Width', 'buzzblogpro'),
			'height' => esc_html__('Height', 'buzzblogpro'),
			'excerpt_length' => esc_html__('Excerpt length (words):', 'buzzblogpro'),
			'link_text' => esc_html__('Link Text:', 'buzzblogpro'),
			'link_url' => esc_html__('Link URL', 'buzzblogpro'),
			'standard' => esc_html__('Standard', 'buzzblogpro'),
			'aside' => esc_html__('Aside', 'buzzblogpro'),
			'quote' => esc_html__('Quote', 'buzzblogpro'),
			'link' => esc_html__('Link', 'buzzblogpro'),
			'image' => esc_html__('Image', 'buzzblogpro'),
			'gallery' => esc_html__('Gallery', 'buzzblogpro'),
			'audio' => esc_html__('Audio', 'buzzblogpro'),
			'video' => esc_html__('Video', 'buzzblogpro'),
			'cat_in' => esc_html__('In', 'buzzblogpro'),
			'categories' => esc_html__('Categories', 'buzzblogpro'),
			'tags' => esc_html__('Tags', 'buzzblogpro'),
			'show_all' => esc_html__('Show All', 'buzzblogpro'),
			'search' => esc_html__('search', 'buzzblogpro'),
			'subscribe' => buzzblogpro_getVariable('subscribe_text') ? buzzblogpro_getVariable('subscribe_text') : esc_html__('Subscribe', 'buzzblogpro'),
			'go' => esc_html__('Go', 'buzzblogpro'),
			'prev_post' => buzzblogpro_getVariable('previously_text') ? buzzblogpro_getVariable('previously_text') : esc_html__('previously', 'buzzblogpro'),
			'next_post' => buzzblogpro_getVariable('upnext_text') ? buzzblogpro_getVariable('upnext_text') : esc_html__('up next', 'buzzblogpro'),
			'url' => esc_html__('URL', 'buzzblogpro'),
			'url_1' => esc_html__('URL #1', 'buzzblogpro'),
			'url_2' => esc_html__('URL #2', 'buzzblogpro'),
			'uncategorized' => esc_html__('Uncategorized', 'buzzblogpro'),
			'last' => esc_html__('Last &rarr;', 'buzzblogpro'),
			'first' => esc_html__('&larr; First', 'buzzblogpro'),
			'delete' => esc_html__('Delete', 'buzzblogpro'),
			'share_on' => buzzblogpro_getVariable('share_on_text') ? buzzblogpro_getVariable('share_on_text') : esc_html__('Share', 'buzzblogpro'),
			//Output Audio
			'prev' => esc_html__('&larr; Previous', 'buzzblogpro'),
			'next' => esc_html__('Next &rarr;', 'buzzblogpro'),
			'play' => esc_html__('Play', 'buzzblogpro'),
			'pause' => esc_html__('Pause', 'buzzblogpro'),
			'stop' => esc_html__('Stop', 'buzzblogpro'),
			'mute' => esc_html__('Mute', 'buzzblogpro'),
			'unmute' => esc_html__('Unmute', 'buzzblogpro'),
			'update_required' => wp_kses( __("<span>Update Required. </span>To play the media you will need to either update your browser to a recent version or update your <a href='http://get.adobe.com/flashplayer/' target='_blank'>Flash plugin</a>.", 'buzzblogpro'), $allowed_html_array ),
			'search_term' => esc_html__('Looking for something in particular?', 'buzzblogpro'),
			
			//Other theme options
			'no_repeat' => esc_html__('No Repeat', 'buzzblogpro'),
			//slideshow
			'view_post' => esc_html__('Read more', 'buzzblogpro'),
			//Gallery options
			'gallery' => esc_html__('Gallery', 'buzzblogpro'),
			'galcategories' => esc_html__('Gallery categories', 'buzzblogpro'),
			'gallery_categorie' => esc_html__('Browsing gallery category', 'buzzblogpro'),
			'view_picture' => esc_html__('View Picture', 'buzzblogpro'),
			
			'gal_our_role' => esc_html__('Our role', 'buzzblogpro'),
'gal_year' => esc_html__('Year', 'buzzblogpro'),
'gal_client' => esc_html__('Client', 'buzzblogpro'),
'gal_technology' => esc_html__('Technology', 'buzzblogpro'),
'gal_url' => esc_html__('Live URL', 'buzzblogpro'),

			//function.php
			'login_error' => esc_html__('The login information you have entered is incorrect.', 'buzzblogpro'),
			'warning_notice_1' => esc_html__('You need to enable write permissions on your server to use these functions.', 'buzzblogpro'),
			'warning_notice_2' => esc_html__('Theme Framework is not able to perform necessary changes for the correct work with your child theme.', 'buzzblogpro'),
			'warning_notice_3' => wp_kses( __('See <a target="_blank" href="http://codex.wordpress.org/Changing_File_Permissions">the Codex</a> for more information.', 'buzzblogpro'), $allowed_html_array ),
			
			//theme-init.php
			'header_menu' => esc_html__('Header Menu', 'buzzblogpro'),
			'footer_menu' => esc_html__('Footer Menu', 'buzzblogpro'),
			'slides' => esc_html__('Slides', 'buzzblogpro'),
			'testimonial' => esc_html__('Testimonial', 'buzzblogpro'),
			'services' => esc_html__('Services', 'buzzblogpro'),
			'faqs' => esc_html__('FAQs', 'buzzblogpro'),
			'our_team' => esc_html__('Our Team', 'buzzblogpro'),
			'category' => esc_html__('Category', 'buzzblogpro'),
			'tag' => esc_html__('Tag', 'buzzblogpro'),
			
			//theme-function.php
			'thumbnail' => esc_html__('Thumbnail', 'buzzblogpro'),
			'your_comment' => esc_html__('Your comment is awaiting moderation.', 'buzzblogpro'),

			
			//theme-postmeta.php
			'quote_settings' => esc_html__('Quote Settings', 'buzzblogpro'),
			'quote' => esc_html__('The Quote', 'buzzblogpro'),
			'quote_desc' => esc_html__('Put your quote in this field.', 'buzzblogpro'),
			'author' => esc_html__('Author', 'buzzblogpro'),
			'author_desc' => esc_html__('Put quote author in this field.', 'buzzblogpro'),
			'link_settings' => esc_html__('Link Settings', 'buzzblogpro'),
			'the_url' => esc_html__('The URL', 'buzzblogpro'),
			'the_url_desc' => esc_html__('Insert the URL you wish to link to.', 'buzzblogpro'),
			'image_settings' => esc_html__('Image Settings', 'buzzblogpro'),
			'title_desc' => esc_html__('Input the video title (for playlist).', 'buzzblogpro'),

			//theme-pagemeta.php
			'category_include' => esc_html__('Category Include', 'buzzblogpro'),
			'category_slug' => esc_html__('The Category Slug', 'buzzblogpro'),
			'category_desc' => esc_html__('Name of the custom category that is displayed on this page. You need to use the slug of the category here.', 'buzzblogpro'),

			//sidebar-init.php
			'sidebar' => esc_html__('Sidebar', 'buzzblogpro'),
			'sidebar_desc' => esc_html__('Located at the right side of pages.', 'buzzblogpro'),
			'footer_1' => esc_html__('Footer Area 1', 'buzzblogpro'),
			'footer_2' => esc_html__('Footer Area 2', 'buzzblogpro'),
			'footer_3' => esc_html__('Footer Area 3', 'buzzblogpro'),
			'footer_4' => esc_html__('Footer Area 4', 'buzzblogpro'),
			'footer_desc' => esc_html__('Located at the bottom of pages.', 'buzzblogpro'),
			'archives' => esc_html__('Archives', 'buzzblogpro'),
			'meta' => esc_html__('Meta', 'buzzblogpro'),
			
			//post-meta.php
			'no_comments' => wp_kses( __('0 Comments', 'buzzblogpro'), $allowed_html_array ),
			'comment' => wp_kses( __('1 Comment', 'buzzblogpro'), $allowed_html_array ),
			'comments' => wp_kses( __('% Comments', 'buzzblogpro'), $allowed_html_array ),
			'comments_link' => esc_html__('comments-link', 'buzzblogpro'),
			'comments_closed' => esc_html__('&nbsp;', 'buzzblogpro'),
			'has_not_tags' => esc_html__('No tags', 'buzzblogpro'),
			'like' => esc_html__('I like it.', 'buzzblogpro'),
			'dislike' => esc_html__('I don\'t like.', 'buzzblogpro'),
			'not_voting' => esc_html__('Only registered users can vote!', 'buzzblogpro'),
			'have_voting' => esc_html__('You have already voted.', 'buzzblogpro'),
			
			//post-nav.php
			'older' => esc_html__('Next page &rarr;', 'buzzblogpro'),
			'newer' => esc_html__('&larr; Previous page', 'buzzblogpro'),
			//gallery-nav
            'nextimage' => esc_html__('NEXT IMAGE', 'buzzblogpro'),
            'previousimage' => esc_html__('PREVIOUS IMAGE', 'buzzblogpro'),
			
			//dialog.php
			'shortcode_options' => esc_html__('Shortcode Options', 'buzzblogpro'),
			'cancel' => esc_html__('Cancel', 'buzzblogpro'),
			'insert_shortcode' => esc_html__('Insert Shortcode', 'buzzblogpro'),
			
			//editor_plugin.php
			'posts' => esc_html__('Posts', 'buzzblogpro'),
			'posts_grid' => esc_html__('Posts Grid', 'buzzblogpro'),
			'posts_list' => esc_html__('Posts List', 'buzzblogpro'),
			'mini_posts_grid' => esc_html__('Mini Posts Grid', 'buzzblogpro'),
			'mini_posts_list' => esc_html__('Mini Posts List', 'buzzblogpro'),
			'recentposts' => esc_html__('Recent Posts', 'buzzblogpro'),
			'recenttesti' => esc_html__('Recent Testimonials', 'buzzblogpro'),
			'basic' => esc_html__('Basic', 'buzzblogpro'),
			'banner' => esc_html__('Banner', 'buzzblogpro'),
			'recentcomments' => esc_html__('Comments', 'buzzblogpro'),
			'post_cycle' => esc_html__('Post Cycle', 'buzzblogpro'),
			'carousel' => esc_html__('Carousel', 'buzzblogpro'),
			'roundabout' => esc_html__('Roundabout', 'buzzblogpro'),
			'service_box' => esc_html__('Service Box', 'buzzblogpro'),
			'hero_unit' => esc_html__('Hero Unit', 'buzzblogpro'),
			'columns' => esc_html__('Columns', 'buzzblogpro'),
			'fluid_column' => esc_html__('Fluid Column', 'buzzblogpro'),
			'2_columns' => esc_html__('2 Columns', 'buzzblogpro'),
			'3_columns' => esc_html__('3 Columns', 'buzzblogpro'),
			'4_columns' => esc_html__('4 Columns', 'buzzblogpro'),
			'elements' => esc_html__('Elements', 'buzzblogpro'),
			'label' => esc_html__('Label', 'buzzblogpro'),
			'highlight' => esc_html__('Text Highlight', 'buzzblogpro'),
			'button' => esc_html__('Button', 'buzzblogpro'),
			'dropcap' => esc_html__('Drop Cap', 'buzzblogpro'),
			'blockquote' => esc_html__('Blockquote', 'buzzblogpro'),
			'icon' => esc_html__('Icon', 'buzzblogpro'),
			'frame' => esc_html__('Frame', 'buzzblogpro'),
			'hr' => esc_html__('Horizontal Rule', 'buzzblogpro'),
			'sm_hr' => esc_html__('Small Horizontal Rule', 'buzzblogpro'),
			'vr' => esc_html__('Vertical Rule', 'buzzblogpro'),
			'spacer' => esc_html__('Spacer', 'buzzblogpro'),
			'progressbar' => esc_html__('Progressbar', 'buzzblogpro'),
			'address' => esc_html__('Address', 'buzzblogpro'),
			'clear' => esc_html__('Clear', 'buzzblogpro'),
			'extra_wrap' => esc_html__('Extra Wrap', 'buzzblogpro'),
			'lists' => esc_html__('Lists', 'buzzblogpro'),
			'list_un' => esc_html__('Unstyled', 'buzzblogpro'),
			'check_list' => esc_html__('Check List', 'buzzblogpro'),
			'check2_list' => esc_html__('Check 2 List', 'buzzblogpro'),
			'arrow_list' => esc_html__('Arrow List', 'buzzblogpro'),
			'arrow2_list' => esc_html__('Arrow 2 List', 'buzzblogpro'),
			'star_list' => esc_html__('Star List', 'buzzblogpro'),
			'plus_list' => esc_html__('Plus List', 'buzzblogpro'),
			'minus_list' => esc_html__('Minus List', 'buzzblogpro'),
			'custom_list' => esc_html__('Custom List', 'buzzblogpro'),
			'audio_video' => esc_html__('Audio & Video', 'buzzblogpro'),
			'video_preview' => esc_html__('Video Preview', 'buzzblogpro'),
			'misc' => esc_html__('Misc', 'buzzblogpro'),
			'alert_box' => esc_html__('Alert Box', 'buzzblogpro'),
			'close' => esc_html__('Close icon', 'buzzblogpro'),
			'well' => esc_html__('Well', 'buzzblogpro'),
			'small' => esc_html__('Small', 'buzzblogpro'),
			'title_box' => esc_html__('Title Box', 'buzzblogpro'),
			'template_url' => esc_html__('Template URL', 'buzzblogpro'),
			'tabs' => esc_html__('Tabs', 'buzzblogpro'),
			'accordions' => esc_html__('Accordion', 'buzzblogpro'),
			'table' => esc_html__('Table', 'buzzblogpro'),
			'map' => esc_html__('Google Map', 'buzzblogpro'),
			'site_map' => esc_html__('Sitemap', 'buzzblogpro'),
			
			//my-banners-widget.php
			'add_125_125' => esc_html__('Add 125x125 ads.', 'buzzblogpro'),
			'add_125_125_desc' => esc_html__('125x125 Ads', 'buzzblogpro'),
			'ad_1' => esc_html__('Ad 1', 'buzzblogpro'),
			'ad_2' => esc_html__('Ad 2', 'buzzblogpro'),
			'ad_3' => esc_html__('Ad 3', 'buzzblogpro'),
			'ad_4' => esc_html__('Ad 4', 'buzzblogpro'),
			'image_ad_link' => esc_html__('Image Ad Link:', 'buzzblogpro'),
			'ad_link' => esc_html__('Ad Link:', 'buzzblogpro'),
			
			//my-comment-widget.php
			'recent_comments' => esc_html__('Recent Comments', 'buzzblogpro'),
			'recent_comments_decs' => esc_html__('My Recent Comments', 'buzzblogpro'),
			'go_to_c' => esc_html__('Go to this comment', 'buzzblogpro'),
			'comments_count' => esc_html__('Number of comments to show', 'buzzblogpro'),
			'display_avatar' => esc_html__('Display avatar', 'buzzblogpro'),
			'avatar_size' => esc_html__('Avatar size (px)', 'buzzblogpro'),
			'display_author_name' => esc_html__('Display the comment author', 'buzzblogpro'),
			'display_date' => esc_html__('Display the comment date', 'buzzblogpro'),
			'display_post_title' => esc_html__('Display post title', 'buzzblogpro'),
			'meta_format' => esc_html__('Meta format', 'buzzblogpro'),
			'comment_date' => esc_html__('Date', 'buzzblogpro'),
			'comment_author' => esc_html__('Author', 'buzzblogpro'),
			'comment_in' => esc_html__('Comment in', 'buzzblogpro'),
			
			//my-flickr-widget.php
			'flickr' => esc_html__('Flickr', 'buzzblogpro'),
			'flickr_id' => esc_html__('Flickr ID:', 'buzzblogpro'),
			'images_count' => esc_html__('Images count:', 'buzzblogpro'),
			
			//my-posts-type-widget.php
			'advanced_cycle' => esc_html__('Advanced Cycle', 'buzzblogpro'),
			'advanced_cycle_desc' => esc_html__('Show custom posts', 'buzzblogpro'),
			'posts_type' => esc_html__('Posts type', 'buzzblogpro'),
			'posts_num' => esc_html__('Number of posts to show', 'buzzblogpro'),
			'sort_by' => esc_html__('Sort by', 'buzzblogpro'),
			'reverse_sort' => esc_html__('Reverse sort order (ascending)', 'buzzblogpro'),
			'show_number' => esc_html__('Show number of comments', 'buzzblogpro'),
			'show_meta' => esc_html__('Show meta', 'buzzblogpro'),
			'container_class' => esc_html__('Container class', 'buzzblogpro'),
			'default_featured_custom' => esc_html__('(default: "featured_custom_posts")', 'buzzblogpro'),
			'post_title' => esc_html__('Post title', 'buzzblogpro'),
			'show_post_title' => esc_html__('Show post title', 'buzzblogpro'),
			'date_as_title' => wp_kses( __("Date as title <span style='font-size:11px; color:#999;'>('[mm-dd-yyyy]')</span>", 'buzzblogpro'), $allowed_html_array ),
			'excerpt' => esc_html__('Excerpt', 'buzzblogpro'),
			'post_excerpt' => esc_html__('Show post excerpt', 'buzzblogpro'),
			'excerpt_link' => esc_html__('Excerpt as link', 'buzzblogpro'),
			'more_link' => esc_html__('More link', 'buzzblogpro'),
			'show_more_link' => esc_html__('Show "More link', 'buzzblogpro'),
			'default_read_more' => esc_html__('(default: "Read more")', 'buzzblogpro'),
			'link_class' => esc_html__('Link class', 'buzzblogpro'),
			'default_link' => esc_html__('(default: "link")', 'buzzblogpro'),
			'thumbnail_dimensions' => esc_html__('Thumbnail dimensions', 'buzzblogpro'),
			'show_post_thumbnail' => esc_html__('Show post thumbnail', 'buzzblogpro'),
			'thumbnail_as_link' => esc_html__('Thumbnail as link', 'buzzblogpro'),
			'all_posts_link' => esc_html__('Link to all posts', 'buzzblogpro'),
			'show_global_link' => esc_html__('Show global link to all posts', 'buzzblogpro'),
			'default_view_all' => esc_html__('(default: "View all")', 'buzzblogpro'),
			
			//my-recent-posts
			'recent_posts' => esc_html__('Recent Posts', 'buzzblogpro'),
			'permanent_link_to' => esc_html__('Permanent Link to', 'buzzblogpro'),
			'category_slug' => esc_html__('Category Slug:', 'buzzblogpro'),
			'post_format' => esc_html__('Post format:', 'buzzblogpro'),
			'post_order' => esc_html__('Post order:', 'buzzblogpro'),
			'posts_per_page' => esc_html__('Posts per page:', 'buzzblogpro'),
			
			//my-social-widget.php
			'social_networks' => esc_html__('Social Networks', 'buzzblogpro'),
			'social_networks_desc' => esc_html__('Link to your social networks.', 'buzzblogpro'),
			//'label' => esc_html__(' label:', 'buzzblogpro'),
			'display' => esc_html__('Display:', 'buzzblogpro'),
			'icons' => esc_html__('Icons', 'buzzblogpro'),
			'labels' => esc_html__('Labels', 'buzzblogpro'),
			'both' => esc_html__('Both', 'buzzblogpro'),
			
			//my-twitter-widget.php
			'twitter' => esc_html__('Twitter', 'buzzblogpro'),
			'twitter_name' => esc_html__('Twitter Name:', 'buzzblogpro'),
			'twitter_num' => esc_html__('Twitts Number:', 'buzzblogpro'),

			//my-facebook-widget.php
'facebook_widget_name' => esc_html__('Facebook Like Box Widget', 'buzzblogpro'),
			'facebook_widget_disc' => esc_html__('Facebook Like Box Widget', 'buzzblogpro'),
			'facebook_url' => esc_html__('Facebook page url', 'buzzblogpro'),
			'facebook_desc' => wp_kses( __('The Like Box only works with <a target="_blank" href="https://www.facebook.com/help/174987089221178/" title="Facebook Pages">Facebook Pages.</a>', 'buzzblogpro'), $allowed_html_array ),
			'color_scheme' => esc_html__('Color Scheme', 'buzzblogpro'),
			'light' => esc_html__('Light', 'buzzblogpro'),
			'dark' => esc_html__('Dark', 'buzzblogpro'),
			'display_haeder' => esc_html__('Hide cover photo in the header', 'buzzblogpro'),
			'display_stream' => esc_html__("Show posts from the Page's timeline.", 'buzzblogpro'),
			'small_header' => esc_html__('Use the small header instead', 'buzzblogpro'),
			'display_faces' => esc_html__('Show profile photos when friends like this', 'buzzblogpro'),
			'facebook_title' => esc_html__('My Facebook Page', 'buzzblogpro'),
			'facebook_error' => esc_html__('Facebook error', 'buzzblogpro'),
			
			//comments.php 
			'post_comment' => buzzblogpro_getVariable('postcomment_text') ? buzzblogpro_getVariable('postcomment_text') : esc_html__('Post comment', 'buzzblogpro'),
			'what_do_you_think' => buzzblogpro_getVariable('whatdoyouthink_text') ? buzzblogpro_getVariable('whatdoyouthink_text') : esc_html__('What do you think?', 'buzzblogpro'),
			'author_name' => esc_html__('Name', 'buzzblogpro'),
			'please_do_not' => esc_html__('Please do not load this page directly. Thanks!', 'buzzblogpro'),
			'password' => esc_html__('This post is password protected. Enter the password to view comments.', 'buzzblogpro'),
			'response' => esc_html__('1 Response', 'buzzblogpro'),
			'responses' => esc_html__('%1$s Responses', 'buzzblogpro'),
			'no_comments_yet' => esc_html__('No Comments Yet.', 'buzzblogpro'),
			'comments_are_closed' => esc_html__('Comments are closed.', 'buzzblogpro'),
			'leave_a_reply' => esc_html__('Leave a comment', 'buzzblogpro'),
			'you_must_be' => esc_html__('You must be', 'buzzblogpro'),
			'post_a_comment' => esc_html__('to post a comment.', 'buzzblogpro'),
			'logged_in' => esc_html__('Logged in', 'buzzblogpro'),
			'logged_in_as' => esc_html__('Logged in as', 'buzzblogpro'),
			'log_account' => esc_html__('Log out of this account;', 'buzzblogpro'),
			'log_out' => esc_html__('Log out &raquo;', 'buzzblogpro'),
			'email_comment' => esc_html__('Email (will not be published)', 'buzzblogpro'),
			'website_comment' => esc_html__('Website', 'buzzblogpro'),
			'your_comment' => esc_html__('Your comment*', 'buzzblogpro'),
			'submit_comment' => esc_html__('Submit Comment', 'buzzblogpro'),
			
			//share-buttons.php
			'tweet_this_article' => esc_html__('Tweet this article', 'buzzblogpro'),
			
			//loop-archives.php
			'continue_reading' => buzzblogpro_getVariable('continuereading_text') ? buzzblogpro_getVariable('continuereading_text') : wp_kses( __("VIEW <em>the</em> POST", 'buzzblogpro'), $allowed_html_array ),
			
			
			
			'pages' => esc_html__('Pages:', 'buzzblogpro'),
			'last_posts' => esc_html__('Last 30 Posts', 'buzzblogpro'),
			'archives_month' => esc_html__('Archives by Month:', 'buzzblogpro'),
			'archives_subject' => esc_html__('Archives by Subject:', 'buzzblogpro'),
			
			//loop-author.php
			'about' => esc_html__('About:', 'buzzblogpro'),
			'recent_posts_by' => esc_html__('Recent Posts by', 'buzzblogpro'),
			'no_post_yet' => esc_html__('No post yet', 'buzzblogpro'),
			'recent_comments_by' => esc_html__('Recent Comments by', 'buzzblogpro'),
			'no_comments_author' => esc_html__('%1$s on %2$s', 'buzzblogpro'),
			'no_comments_by' => esc_html__('No comments by', 'buzzblogpro'),
			'yet' => esc_html__('yet.', 'buzzblogpro'),
			
			//loop-blog.php //loop-single-testi.php
			'there_has' => esc_html__('There has been an error.', 'buzzblogpro'),
			'we_apologize' => esc_html__('We apologize for any inconvenience, please', 'buzzblogpro'),
			'return_to' => esc_html__('return to the home page', 'buzzblogpro'),
			'search_form' => esc_html__('or use the search form below.', 'buzzblogpro'),
			
			
			//loop-single.php
			'written_by' => esc_html__('Written by', 'buzzblogpro'),
			'view_all' => esc_html__('View all posts by', 'buzzblogpro'),
			
			//portfolio-loop.php
			'not_found' => esc_html__('Not Found', 'buzzblogpro'),
			'apologies' => esc_html__('Apologies, but no results were found for the requested archive. Perhaps searching will help find a related post.', 'buzzblogpro'),
			
			//title.php
			'category_archives' => esc_html__('You are viewing', 'buzzblogpro'),
			'portfolio_category' => esc_html__('Portfolio Category', 'buzzblogpro'),
			'fearch_for' => esc_html__('Search for', 'buzzblogpro'),
			'posts_by_type' => esc_html__('Posts by type', 'buzzblogpro'),
			'daily_archives' => esc_html__('Daily Archives', 'buzzblogpro'),
			'monthly_archives' => esc_html__('Monthly Archives', 'buzzblogpro'),
			'yearly_archives' => esc_html__('Yearly Archives', 'buzzblogpro'),
			'by' => esc_html__('All Posts By ', 'buzzblogpro'),
			'tag_archives' => esc_html__('Tag Archives', 'buzzblogpro'),
			'portfolio_tag' => esc_html__('Portfolio Tag', 'buzzblogpro'),
			
			//header.php
			'category_for' => esc_html__('Category Archive for', 'buzzblogpro'),
			'tag_for' => esc_html__('Tag Archive for', 'buzzblogpro'),
			'archive' => esc_html__('Archive', 'buzzblogpro'),
			'error_404' => esc_html__('Error 404 Not Found', 'buzzblogpro'),
			
			//loop-single-portfolio.php
			'launch_project' => esc_html__('Launch Project', 'buzzblogpro'),
			
			//static-not-found.php
			'sorry' => esc_html__('Sorry!', 'buzzblogpro'),
			'page_not_found' => esc_html__('Page Not Found', 'buzzblogpro'),
			'page_you_are_looking' => esc_html__('The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.', 'buzzblogpro'),
			'please_try_using' => esc_html__('Please try using our search box below.', 'buzzblogpro'),
			
			//posts_list.php
			'posted_in' => esc_html__('Posted in', 'buzzblogpro'),

			//standard.php
			'featured' => esc_html__('Featured', 'buzzblogpro')
			);
		return $locals[$label];
	};
?>